config/routes.rb
Rails.application.routes.draw do
  resources :customers
  root 'welcomes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path, notice: 'Cliente cadastrado com sucesso!'
    else
      render :new
    end
    def customer_params
      params.require(:customer).permit(:id, :name, :email, :smoker, :phone, :avatar )
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/index.html.erb
<% if flash[:notice ] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h1>Listando Clientes</h1>
<%= link_to "Novo Cliente", new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>

<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.label :smoker %> <br />
  <% {'S': 'Sim', 'N': 'Não'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %> <br />
    <% end %>

  <%= f.submit 'Criar Cliente' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/index.html.erb
<H1>Bem-Vindo</H1>

<ul>
  <li><%= link_to "Cadastro de Clientes", customers_path %></li>
</ul>